export const ActionTypes = {
  SET_PIZZAS: 'SET_PIZZAS',
  ADD_PIZZA_TO_CART: 'ADD_PIZZA_TO_CART',
  REMOVE_PIZZA_FROM_CART: 'REMOVE_PIZZA_FROM_CART',
  GET_CART: 'GET_CART',
  CLEAR_CART: 'CLEAR_CART'
};
